### ISSUE TITLE
Limited Tutorial Creation Options

### ISSUE THREAD

**Issue by pauloebveiga** [SlicerLatinAmerica/SlicerTutorialMaker#19]
Problem: the current tutorial creation process seems restricted to Slicer4minutes, thereby excluding others tutorials.

Description: there are several tutorials that require updates, in addition to the initial tutorial (Slicer4minutes). It would be beneficial to consider including other tutorials in the tutorial maker database.

**Comment by DouSam** [comment]
Just an update, we are creating the repositories with the tutorials, now we have the 4minute completed and the incomplete welcome tutorial.

**Comment by DouSam** [comment]
We have created the repository https://github.com/SlicerLatinAmerica/TestSlicerTutorials with the tutorials, now, when you open the extension, the tutorials are loaded from this repository.
