### ISSUE TITLE
Four Minute Tutorial prototype

### ISSUE THREAD

**Issue by spujol** [SlicerLatinAmerica/SlicerTutorialMaker#40]
In slide #4 and slide #9 of the version of the Slicer Four Minute tutorial created by the Tutorial Maker tool, the text 'Axial' and 'grayscale' and 'Coronal' 'grayscale' appear distorted in the left panel.

In all the slides: please replace 'add tittle' with 'add title' here.

![Screenshot 2024-12-02 at 11 58 24 AM](https://github.com/user-attachments/assets/83ba50a6-7330-4079-84f0-bf1b27d6884f)

**Comment by DouSam** [comment]
Done, the popouts will appear in the same screenshot of the main window.
