### ISSUE TITLE
Slicer Tutorial Maker : Robustness issue

### ISSUE THREAD

**Issue by spujol** [SlicerLatinAmerica/SlicerTutorialMaker#48]
I tried to run the Four Minute tutorial twice. The first time the Annotator tool enabled me to annotate the screenshots. However, I was unable to save the tutorial as a pdf or Markdown file.

I clicked on Run and Annotate again. The Tutorial Maker tool repeated the Slicer 4 Minute workflow, but stopped at the Red Slice Clipping step and did not proceed further.

I restarted Slicer: the tutorial Maker tool stopped again at the Red Slice Clipping step.

Traceback (most recent call last):
  File "/Users/smp36/spujol/software/SlicerTutorialMaker-main/TutorialMaker/TutorialMaker.py", line 161, in annotateButton
    self.logic.Annotate(self.__selectedTutorial)
  File "/Users/smp36/spujol/software/SlicerTutorialMaker-main/TutorialMaker/TutorialMaker.py", line 221, in Annotate
    TutorialMakerTest().test_TutorialMaker1(tutorialName)
  File "/Users/smp36/spujol/software/SlicerTutorialMaker-main/TutorialMaker/TutorialMaker.py", line 309, in test_TutorialMaker1
    tutorial.runTest()
  File "/Users/smp36/spujol/software/SlicerTutorialMaker-main/TutorialMaker/Testing/fourMin_tutorial.py", line 25, in runTest
    self.test_Slicer4Minute1()
  File "/Users/smp36/spujol/software/SlicerTutorialMaker-main/TutorialMaker/Testing/fourMin_tutorial.py", line 120, in test_Slicer4Minute1
    clip.SetRedSliceClipState(0)
AttributeError: 'MRMLCorePython.vtkMRMLClipNode' object has no attribute 'SetRedSliceClipState'

Slicer 5.7 on Mac OSX 14.6.1

![Screenshot 2024-12-07 at 10 54 23 AM](https://github.com/user-attachments/assets/70bea7da-b3de-4656-88dc-32d963fd65dc)

**Comment by spujol** [comment]
I removed the Tutorial Maker module from the list of modules and restarted Slicer. 

I reinstalled the module and re-ran the Four Minute tutorial. The bug remains the same.

witch to module:  "TutorialMaker"
Starting the test
Switch to module:  "Welcome"
goodbye, world!
Screenshot #1: In the Welcome screen.
Verifying checksum
File already exists and checksum is OK - reusing it.
<b>Requesting load /Users/smp36/Library/Caches/slicer.org/Slicer/SlicerIO/slicer4minute.mrb</b>
Warning: In vtkMRMLCameraNode.cxx, line 414
vtkMRMLCameraNode (0x7fbcf7d1bdd0): vtkMRMLCameraNode::SetActiveTag() is deprecated. Use vtkMRMLCameraNode::SetLayoutName() instead.


Warning: In vtkMRMLCameraNode.cxx, line 414
vtkMRMLCameraNode (0x7fbcf7d920a0): vtkMRMLCameraNode::SetActiveTag() is deprecated. Use vtkMRMLCameraNode::SetLayoutName() instead.


Warning: In vtkMRMLCameraNode.cxx, line 414
vtkMRMLCameraNode (0x7fbcf7e0c8c0): vtkMRMLCameraNode::SetActiveTag() is deprecated. Use vtkMRMLCameraNode::SetLayoutName() instead.


/Applications/Slicer 3.app/Contents/bin/Python/slicer/util.py:2811: UserWarning: already has observer
  warn("already has observer")
ReadDataInternal (vtkMRMLModelStorageNode1): File /Users/smp36/Library/Caches/slicer.org/Slicer/SlicerIO/_tmp20241207wQj99/slicer4minute/Data/hemispheric_white_matter.vtk does not contain coordinate system information. Assuming RAS.


ReadDataInternal (vtkMRMLModelStorageNode2): File /Users/smp36/Library/Caches/slicer.org/Slicer/SlicerIO/_tmp20241207wQj99/slicer4minute/Data/left_eyeball.vtk does not contain coordinate system information. Assuming RAS.


ReadDataInternal (vtkMRMLModelStorageNode3): File /Users/smp36/Library/Caches/slicer.org/Slicer/SlicerIO/_tmp20241207wQj99/slicer4minute/Data/optic_chiasm.vtk does not contain coordinate system information. Assuming RAS.


ReadDataInternal (vtkMRMLModelStorageNode4): File /Users/smp36/Library/Caches/slicer.org/Slicer/SlicerIO/_tmp20241207wQj99/slicer4minute/Data/optic_nerve_L.vtk does not contain coordinate system information. Assuming RAS.


ReadDataInternal (vtkMRMLModelStorageNode5): File /Users/smp36/Library/Caches/slicer.org/Slicer/SlicerIO/_tmp20241207wQj99/slicer4minute/Data/optic_nerve_R.vtk does not contain coordinate system information. Assuming RAS.


ReadDataInternal (vtkMRMLModelStorageNode6): File /Users/smp36/Library/Caches/slicer.org/Slicer/SlicerIO/_tmp20241207wQj99/slicer4minute/Data/optic_tract_L.vtk does not contain coordinate system information. Assuming RAS.


ReadDataInternal (vtkMRMLModelStorageNode7): File /Users/smp36/Library/Caches/slicer.org/Slicer/SlicerIO/_tmp20241207wQj99/slicer4minute/Data/optic_tract_R.vtk does not contain coordinate system information. Assuming RAS.


ReadDataInternal (vtkMRMLModelStorageNode8): File /Users/smp36/Library/Caches/slicer.org/Slicer/SlicerIO/_tmp20241207wQj99/slicer4minute/Data/right_eyeball.vtk does not contain coordinate system information. Assuming RAS.


ReadDataInternal (vtkMRMLModelStorageNode9): File /Users/smp36/Library/Caches/slicer.org/Slicer/SlicerIO/_tmp20241207wQj99/slicer4minute/Data/Skin.vtk does not contain coordinate system information. Assuming RAS.


ReadDataInternal (vtkMRMLModelStorageNode10): File /Users/smp36/Library/Caches/slicer.org/Slicer/SlicerIO/_tmp20241207wQj99/slicer4minute/Data/skull_bone.vtk does not contain coordinate system information. Assuming RAS.


ID: vtkMRMLClipNodevtkMRMLClipModelsNode
ClassName: vtkMRMLClipNode
Name: ClipModelsParameters1
Debug: false
MTime: 332682
Description: (none)
SingletonTag: vtkMRMLClipModelsNode
HideFromEditors: true
Selectable: true
Selected: false
UndoEnabled: false
Node references:
  clipping [clippingRef]: vtkMRMLSliceNodeRed: {clipingState: ClipOff} vtkMRMLSliceNodeYellow: {clipingState: ClipOff} vtkMRMLSliceNodeGreen: {clipingState: ClipOff}
ClipType: ClipIntersection
ClippingMethod: Straight
"MRB Slicer Data Bundle" Reader has successfully read the file "/Users/smp36/Library/Caches/slicer.org/Slicer/SlicerIO/slicer4minute.mrb" "[0.21s]"
<b>Load finished</b><p></p>
Finished with download and loading
Switch to module:  "Models"
Screenshot #2: In the Models screen with the sample data loaded.
Screenshot #3: With the red view panel opened.
Screenshot #4: With the red view slided to -57.
Screenshot #5: With the skin node selected and opacity lowered to 0,5.
Screenshot #6: Change the visibility of skin to 0 and rotate de camera to show the top of the head.
Screenshot #7: Set the visibility of the green view, showing the two view panel.
Screenshot #8: Change the visibility of skull_bone, also click in the skull_bone in the node list.
Traceback (most recent call last):
  File "/Users/smp36/spujol/software/SlicerTutorialMaker-main/TutorialMaker/TutorialMaker.py", line 161, in annotateButton
    self.logic.Annotate(self.__selectedTutorial)
  File "/Users/smp36/spujol/software/SlicerTutorialMaker-main/TutorialMaker/TutorialMaker.py", line 221, in Annotate
    TutorialMakerTest().test_TutorialMaker1(tutorialName)
  File "/Users/smp36/spujol/software/SlicerTutorialMaker-main/TutorialMaker/TutorialMaker.py", line 309, in test_TutorialMaker1
    tutorial.runTest()
  File "/Users/smp36/spujol/software/SlicerTutorialMaker-main/TutorialMaker/Testing/fourMin_tutorial.py", line 25, in runTest
    self.test_Slicer4Minute1()
  File "/Users/smp36/spujol/software/SlicerTutorialMaker-main/TutorialMaker/Testing/fourMin_tutorial.py", line 120, in test_Slicer4Minute1
    clip.SetRedSliceClipState(0)
AttributeError: 'MRMLCorePython.vtkMRMLClipNode' object has no attribute 'SetRedSliceClipState'

**Comment by lassoan** [comment]
This is due to an API change in Slicer (the entire clipping infrastructure was redesigned recently in Slicer-5.7). I'll try to fix this now.

**Comment by DouSam** [comment]
@lassoan that brings me a doubt. When Slice updates, do they don't keep the functions as deprecated? They just remove the functions?
So here we will have to create two versions of the 4minute test, 1 for 5.7 and above and another for below?

**Comment by LuskasHusty** [comment]
We could keep the different versions as branches on their repos. When we pull the tutorials using the TutorialMaker git lib  we could check for version compatibility no? @DouSam

**Comment by lassoan** [comment]
In general, backward compatibility is maintained, but if needed then we can make the script work slightly differently depending on the Slicer version (see the current fix - https://github.com/SlicerLatinAmerica/SlicerTutorialMaker/pull/53).
