### ISSUE TITLE
Annotator tool: Adding descriptive text to an arrow

### ISSUE THREAD

**Issue by spujol** [SlicerLatinAmerica/SlicerTutorialMaker#49]
The widget for adding descriptive text to an arrow currently appears blank, making it unintuitive for end-users to know where to input text.

To improve usability, consider adding a placeholder or default text, such as:
"Add text to accompany an arrow here."

This would guide users on how to use the feature effectively.

![Screenshot 2024-12-07 at 11 54 02 AM](https://github.com/user-attachments/assets/121fb2a0-1fd9-4e5e-8070-ad6d3ccdbfdc)

**Comment by vmms** [comment]
Add the caption "Add text to accompany an arrow here." to make the use of text with arrows more intuitive. This caption appears every time a screenshot is selected in the thumbnail sidebar.

When the caption "Add text to accompany an arrow here" is not present or there is no text, the arrow is painted alone without the text box.
![Captura de pantalla 2024-12-10 a la(s) 2 34 44 p m](https://github.com/user-attachments/assets/bce65da4-89b4-41ed-80c9-27b5e6c0f89c)

**Comment by DouSam** [comment]
I have merged this version in the main branch. I will consider this done, if you disagree, please, reopen the issue with the screenshot of the situation.
