### ISSUE TITLE
Field to add text to accompany an arrow is not working

### ISSUE THREAD

**Issue by DouSam** [SlicerLatinAmerica/SlicerTutorialMaker#58]
We are testing the extension and when the font size of the application is above 14p or something like that the field stops appearing.
![image](https://github.com/user-attachments/assets/c6763e72-acbd-4aa1-97d3-71327ad52349)
When we set the size for 20p
![image](https://github.com/user-attachments/assets/98429dc9-1226-432a-8c01-dd4965fc96a1)
Probably because the input is size-fixed. We are trying to solve that.

**Comment by LuskasHusty** [comment]
@DouSam In tutorial GUI.py
![image](https://github.com/user-attachments/assets/5060eab0-89f0-47ee-842b-46e6007e6aa8)

**Comment by DouSam** [comment]
@LuskasHusty yeah... I changed it to "setMaximumWidth()".
![image](https://github.com/user-attachments/assets/305c11b0-eb7b-409e-b0d4-5dbf9bd19c05)
